# Mudan reservoir survey
grid:
  epsg: 3826
  resolution: 0.5
  bounds:
    left: 227173.5
    right: 228429.5
    bottom: 2448218.0
    top: 2449210.5

environment:
  sound_speed: 1489.073    # fresh water at 25°C

mbes:
  source: data/multibeam/G1m_142m.txt
  bathymetry_tif: outputs/tif/mbes_bathymetry.tif
  vrm_tif: outputs/tif/mbes_vrm.tif

sss:
  channels: [HF_port, HF_stbd]    # swap to [LF_port, LF_stbd] for LF

  survey_dirs:
    - path: data/sss/20251223
      cable_length: 15.0
    - path: data/sss/20251224
      cable_length: null

  outputs:
    bs_hf_tif: outputs/tif/sss_backscatter_hf.tif
    lbl_hf_tif: outputs/tif/sss_clusters_hf.tif
    bs_lf_tif: outputs/tif/sss_backscatter_lf.tif
    lbl_lf_tif: outputs/tif/sss_clusters_lf.tif
    validation_dir: outputs/sss_validation

  cluster:
    method: kmeans
    k_init: 7

sbp:
  # Calibration coefficient (run calibrate_sbp_cc.py to estimate)
  calibration_constant: 3.7134e+04

  survey_dirs:
     - path: data/sbp

  outputs:
    rl_tif: outputs/tif/sbp_rl.tif
    sediment_tif: outputs/tif/sbp_sediment_class.tif
    confidence_tif: outputs/tif/sbp_confidence.tif
    isopach_tif: outputs/tif/sbp_isopach.tif